
/*
  This is batch bundling files into one file for spacetimedb since there is circular dependency on multiples files loading order.

  It due to how Schedule Tables works. It need table with Reducers which need to init schema to work with Reducers.

  const reminder = table({
    //...
    scheduled: (): any => send_reminder
  },{
    //...
  })
  const spacetimedb = schema({
    reminder,
  })

  const send_reminder = spacetimedb.reducer(...);
*/
// @ts-ignore
import fs from 'fs';
// @ts-ignore
import path from 'path';
// @ts-ignore
const SRC_DIR = path.join(process.cwd(), 'src');
// @ts-ignore
const OUTPUT_FILE = path.join(process.cwd(), 'src', 'index.ts');

const IGNORE_LIST = [
  'module.ts', // needed for typescript error remove.
  // 'types.ts',
  'index.ts', 
  'helper.ts', 
  'index.js', 
  '.git', 
  'node_modules', 
  'dist'
];

function shouldIgnore(filePath: string): boolean {
  if (filePath === OUTPUT_FILE) return true;
  const relative = path.relative(SRC_DIR, filePath);
  return IGNORE_LIST.some(ignore => relative.includes(ignore));
}
// dir files current from build.ts
function collectFiles(dir: string, files: string[] = []): string[] {
  const items = fs.readdirSync(dir);
  for (const item of items) {
    const fullPath = path.join(dir, item);
    if (shouldIgnore(fullPath)) continue;

    if (fs.statSync(fullPath).isDirectory()) {
      collectFiles(fullPath, files);
    } else if (item.endsWith('.ts') && !item.startsWith('index')) {
      files.push(fullPath);
    }
  }
  return files;
}

function getTag(filePath: string): 'type' | 'table' | 'reducer' | 'procedure' | 'view' | 'lifecycle' | 'other' {
  const content = fs.readFileSync(filePath, 'utf-8').toLowerCase();

  if (content.includes('// types:') || content.includes('// type:')) return 'type';
  if (content.includes('// table:')) return 'table';
  if (content.includes('// reducer:')) return 'reducer';
  if (content.includes('// procedure:')) return 'procedure';
  if (content.includes('// view:')) return 'view';
  if (content.includes('// init') || 
      content.includes('// onconnect') || 
      content.includes('// ondisconnect') || 
      content.includes('// lifecycle')) return 'lifecycle';
  return 'other';
}

async function build() {
  console.log('🔍 Collecting source files...');
  const allFiles = collectFiles(SRC_DIR);
  // check files for keyword since folder in types.
  const types      = allFiles.filter(f => getTag(f) === 'type');
  const tables      = allFiles.filter(f => getTag(f) === 'table');
  const lifecycles  = allFiles.filter(f => getTag(f) === 'lifecycle');
  const reducers    = allFiles.filter(f => getTag(f) === 'reducer');
  const procedures  = allFiles.filter(f => getTag(f) === 'procedure');
  const views       = allFiles.filter(f => getTag(f) === 'view');
  const others      = allFiles.filter(f => getTag(f) === 'other');

  // console.log(types);

  console.log(`Found ${allFiles.length} files → Tables: ${tables.length}`);

  let output = `// =============================================\n`;
  output += `// AUTO-GENERATED by build.ts - DO NOT EDIT THIS FILE!\n`;
  output += `// Generated: ${new Date().toISOString()}\n`;
  output += `// =============================================\n\n`;

  output += `import { schema, table, t } from 'spacetimedb/server';\n`;
  output += `import { ScheduleAt } from 'spacetimedb';\n`;

  output += `import { 
  type Matrix2D, 
  computeLocal2DMatrix, 
  extractPositionFromMatrix, 
  extractRotationFromMatrix, 
  extractScaleFromMatrix, 
  getParentWorld2DMatrix, 
  identity, 
  multiply2D 
} from './helper';\n`;


  // output += `import { Vect2, Transform2DResult } from './types';\n\n`;

  // === 0. CUSTOM TYPES FIRST (remove export, just like tables) ===
  output += `// === CUSTOM TYPES (must come before tables) ===\n\n`;

  for (const file of types) {
    let content = fs.readFileSync(file, 'utf-8')
      .replace(/^import .*$/gm, '')
      .replace(/^export\s+const\s+/gm, 'const ')   // ← Remove export from types
      .replace(/^\/\/\s*(type|types|table|reducer|procedure|view|lifecycle):?.*$/gm, '')
      .replace(/^\s*[\r\n]+/gm, '')
      .trim();

    if (content) {
      output += `// === Type from: ${path.relative(SRC_DIR, file)} ===\n`;
      output += content + '\n\n';
    }
  }


  // 1. TABLES FIRST (without 'export')
  for (const file of tables) {
    let content = fs.readFileSync(file, 'utf-8')
      .replace(/^import .*$/gm, '')
      .replace(/^export\s+const\s+/gm, 'const ')           // ← Remove 'export' from tables
      .replace(/^\/\/\s*(table|reducer|procedure|view|lifecycle):?.*$/gm, '')
      .replace(/^\s*[\r\n]+/gm, '')
      .trim();

    if (content) {
      output += `// === Table from: ${path.relative(SRC_DIR, file)} ===\n`;
      output += content + '\n\n';
    }
  }

  // 2. Collect table names for schema()
  const tableNames: string[] = [];
  tables.forEach(file => {
    const content = fs.readFileSync(file, 'utf-8');
    const match = content.match(/\/\/\s*table:\s*(\w+)/i);
    if (match && match[1]) {
      tableNames.push(match[1].trim());
    }
  });

  // 3. SCHEMA() — AFTER TABLES
  output += `// === SCHEMA (must come before reducers, procedures, views, etc.) ===\n`;
  output += `const spacetimedb = schema({\n`;
  tableNames.forEach((name, i) => {
    output += `  ${name}${i < tableNames.length - 1 ? ',' : ''}\n`;
  });
  output += `});\n\n`;

  // 4. LIFECYCLE + REDUCERS + PROCEDURES + VIEWS (AFTER SCHEMA)
  output += `// === LIFECYCLE HOOKS, REDUCERS, PROCEDURES & VIEWS ===\n\n`;

  const postSchemaFiles = [...lifecycles, ...reducers, ...procedures, ...views, ...others];

  for (const file of postSchemaFiles) {
    let content = fs.readFileSync(file, 'utf-8')
      .replace(/^import .*$/gm, '')
      .replace(/^\/\/\s*(table|reducer|procedure|view|lifecycle):?.*$/gm, '')
      .replace(/^\s*[\r\n]+/gm, '')
      .trim();

    if (content) {
      const tag = getTag(file);
      const displayTag = tag === 'lifecycle' ? 'Lifecycle' : tag.charAt(0).toUpperCase() + tag.slice(1);
      output += `// === ${displayTag} from: ${path.relative(SRC_DIR, file)} ===\n`;
      output += content + '\n\n';
    }
  }

  //should be last
  output += `export default spacetimedb;\n\n`;

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');

  console.log(`✅ Build completed successfully!`);
  console.log(`   Types       : ${types.length}`);
  console.log(`   Tables      : ${tables.length}`);
  console.log(`   Lifecycle   : ${lifecycles.length}`);
  console.log(`   Reducers    : ${reducers.length}`);
  console.log(`   Procedures  : ${procedures.length}`);
  console.log(`   Views       : ${views.length}`);
}

build().catch((err) => {
  console.error('❌ Build failed:', err.message);
  // @ts-ignore
  process.exit(1);
});